version: '2'
services:
  python-dev:
    build:
      context: python-dev
      args:
        - USER
    stdin_open: true
    ports:
     - "8888:8888"
    tty: true
    volumes:
       - ./workdir:/home/${USER}/workdir
